### ISSUE TITLE
Problem running invoker tests that expect a failure inside WildFly

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi-tck#558]
I added the ability to run the core tests inside wildfly with the updated weld jars, and I'm seeing the new invoker tests that expect a failure not generating a failure when run inside of wildfly. The log was showing:

```
2024-02-28 22:23:34,931 WARN  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0007: Could not load portable extension class org.jboss.cdi.tck.tests.invokers.invalid.InterceptorInvokerTest$TestExtension: java.lang.ClassNotFoundException: org.jboss.cdi.tck.tests.invokers.invalid.InterceptorInvokerTest$TestExtension from [Module "deployment.InterceptorInvokerTest9f51e3b08633d3c9a9e67467c893989d5bedfe9.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        at org.jboss.as.weld@31.0.0.Final//org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.loadExtension(WeldPortableExtensionProcessor.java:140)
        at org.jboss.as.weld@31.0.0.Final//org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.loadExtensions(WeldPortableExtensionProcessor.java:94)
        at org.jboss.as.weld@31.0.0.Final//org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.loadAttachments(WeldPortableExtensionProcessor.java:80)
        at org.jboss.as.weld@31.0.0.Final//org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.deploy(WeldPortableExtensionProcessor.java:59)
        at org.jboss.as.server@23.0.1.Final//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:172)
...
```

So looking at the tests, they were not adding the BuildCompatibleExtension to the test archive, so I fixed that, but then the deployments failed to generate an error due to:

```
2024-02-28 22:27:27,194 INFO  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 1) WELD-000119: Not generating any bean definitions from org.jboss.cdi.tck.tests.invokers.invalid.InterceptorInvokerTest$MyInterceptor because of underlying class loading error: Type org.jboss.cdi.tck.tests.invokers.invalid.InterceptorInvokerTest from [Module "deployment.InterceptorInvokerTest9f51e3b08633d3c9a9e67467c893989d5bedfe9.war" from Service Module Loader] not found.  If this is unexpected, enable DEBUG logging to see the full error.
2024-02-28 22:27:27,361 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 32) WFLYUT0021: Registered web context: '/InterceptorInvokerTest9f51e3b08633d3c9a9e67467c893989d5bedfe9' for server 'default-server'
```

All of the inner classes used by the InterceptorInvokerTest are static, so I'm not clear on why there is an attempt to load the InterceptorInvokerTest class. Maybe something I'm not familiar with regarding inner classes. It does seem as though weld should be generating an exception here rather than log logging an error. I'll create a separate issue for that.

I have just refactored the tests to not use inner classes and I have all core tck tests passing with embedded weld as well as when run from within wildfly.

**Comment by Ladicek** [comment]
I see that most of the invokers test don't add the BCExtension into the test archive, which is probably a mistake.

The test class should be in the archive, so even though I'm not sure why Weld would try to load it, it should work :shrug:

**Comment by manovotn** [comment]
> I see that most of the invokers test don't add the BCExtension into the test archive, which is probably a mistake.
> 
> The test class should be in the archive, so even though I'm not sure why Weld would try to load it, it should work 🤷

Seems like Weld will try to make sure each declaring class is loadable [in this code](https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/util/reflection/Reflections.java#L423-L434).
Though I cannot understand why the test class class isn't :thinking:

**Comment by manovotn** [comment]
Ok, so when I look at the resulting (WAR) archive Arq. generates, the test class is *not* part of it, despite being explicitly added in the test.

And looking into how we build test archive, I found that [this bit](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/shrinkwrap/ArchiveBuilder.java#L1281-L1284) will exclude the class if it is running in client mode and the class name equals to the test name. And while I don't recall what the client mode really was (but apparently we are running in it), this seems very deliberate :)
Maybe this rings a bell @Ladicek or @starksm64?

**Comment by Ladicek** [comment]
We apparently treat tests that are expected to fail as "run as client" due to https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/shrinkwrap/ArchiveBuilder.java#L1344 Frankly, that's rather weird...

**Comment by starksm64** [comment]
So in the process of trying to create a reproducer for a WELD issue, I
updated to the 31.0.1.Final version and now I do see an exception, but it
is a org.jboss.weld.exceptions.DefinitionExceptio rather than the expected.
It looks like all invoker tests are failing under that version of wildfly.

```
[ERROR]   ConstructorInvokerTest>Arquillian.arquillianBeforeClass:99 »
Deployment Cannot deploy
ConstructorInvokerTest35162967636eea6857b4c0ace3be8bce6ffebd.war:
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that
failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" =>
{"jboss.deployment.unit.\"ConstructorInvokerTest35162967636eea6857b4c0ace3be8bce6ffebd.war\".WeldStartService"
=> "Failed to start service
    Caused by: org.jboss.weld.exceptions.DefinitionException: Exception
List with 1 exceptions:
Exception 0 :
jakarta.enterprise.event.ObserverException
        at
java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at
java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at
java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
        at java.base/java.lang.Class.newInstance(Class.java:725)
        at ***@***.***
//org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at
java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at ***@***.***
//org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at ***@***.***
//org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
        at ***@***.***
//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:107)
        at ***@***.***
//org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:199)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:342)
        at ***@***.***
//org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:136)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:320)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:298)
        at
jakarta.enterprise.api//jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
        at ***@***.***
//org.jboss.weld.util.Observers.notify(Observers.java:176)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:303)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:289)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:184)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:178)
        at ***@***.***
//org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at ***@***.***
//org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:45)
        at ***@***.***
//org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.fire(BeforeBeanDiscoveryImpl.java:55)
        at ***@***.***
//org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:410)
        at ***@***.***
//org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:80)
        at ***@***.***
//org.jboss.as.weld.WeldStartService.start(WeldStartService.java:79)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
        at ***@***.***
//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError:
jakarta/enterprise/inject/build/compatible/spi/InvokerFactory
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at
java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionInvoker.lambda$findExtensionMethods$0(ExtensionInvoker.java:50)
        at
java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at
java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
        at
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at
java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at
java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionInvoker.findExtensionMethods(ExtensionInvoker.java:64)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionPhaseBase.run(ExtensionPhaseBase.java:29)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.LiteExtensionTranslator.discovery(LiteExtensionTranslator.java:63)
        at
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at ***@***.***
//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:99)
        ... 25 more
Caused by: java.lang.ClassNotFoundException:
jakarta.enterprise.inject.build.compatible.spi.InvokerFactory from [Module
\"deployment.ConstructorInvokerTest35162967636eea6857b4c0ace3be8bce6ffebd.war\"
from Service Module Loader]
        at
org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
        at
org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at
org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at
org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 42 more
"}}}}
```

See https://issues.redhat.com/browse/WELD-2782 for how to reproduce.

**Comment by manovotn** [comment]
> Caused by: java.lang.NoClassDefFoundError:
jakarta/enterprise/inject/build/compatible/spi/InvokerFactory

@starksm64 does your WFLY have latest CDI API in it?
I had a patching profile in core repo for this (that CI uses as well), see https://github.com/weld/core/blob/master/jboss-as/pom.xml#L214-L217

**Comment by starksm64** [comment]
Basically all of the invoker tests appear to be failing with a CNFE on
jakarta.enterprise.inject.build.compatible.spi.InvokerFactory, so the
wildfly modules must not be updated correctly or something is missing.

```
[ERROR]   VoidMethodInvokerTest>Arquillian.arquillianBeforeClass:99 »
Deployment Cannot deploy
VoidMethodInvokerTestfee3f7268256c72de774ea3e923d56c6497eac9.war:
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that
failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" =>
{"jboss.deployment.unit.\"VoidMethodInvokerTestfee3f7268256c72de774ea3e923d56c6497eac9.war\".WeldStartService"
=> "Failed to start service
    Caused by: org.jboss.weld.exceptions.DefinitionException: Exception
List with 1 exceptions:
Exception 0 :
jakarta.enterprise.event.ObserverException
        at
java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at
java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at
java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at
java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
        at java.base/java.lang.Class.newInstance(Class.java:725)
        at ***@***.***
//org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at
java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at ***@***.***
//org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at ***@***.***
//org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
        at ***@***.***
//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:107)
        at ***@***.***
//org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:199)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:342)
        at ***@***.***
//org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:136)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:320)
        at ***@***.***
//org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:298)
        at
jakarta.enterprise.api//jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
        at ***@***.***
//org.jboss.weld.util.Observers.notify(Observers.java:176)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:303)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:289)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:184)
        at ***@***.***
//org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:178)
        at ***@***.***
//org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at ***@***.***
//org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:45)
        at ***@***.***
//org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.fire(BeforeBeanDiscoveryImpl.java:55)
        at ***@***.***
//org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:410)
        at ***@***.***
//org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:80)
        at ***@***.***
//org.jboss.as.weld.WeldStartService.start(WeldStartService.java:79)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
        at ***@***.***
//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
        at ***@***.***
//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at ***@***.***
//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoClassDefFoundError:
jakarta/enterprise/inject/build/compatible/spi/InvokerFactory
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at
java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
        at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionInvoker.lambda$findExtensionMethods$0(ExtensionInvoker.java:50)
        at
java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at
java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
        at
java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at
java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at
java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at
java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at
java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionInvoker.findExtensionMethods(ExtensionInvoker.java:64)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.ExtensionPhaseBase.run(ExtensionPhaseBase.java:29)
        at ***@***.***
//org.jboss.weld.lite.extension.translator.LiteExtensionTranslator.discovery(LiteExtensionTranslator.java:63)
        at
java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at ***@***.***
//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:99)
        ... 25 more
Caused by: java.lang.ClassNotFoundException:
jakarta.enterprise.inject.build.compatible.spi.InvokerFactory from [Module
\"deployment.VoidMethodInvokerTestfee3f7268256c72de774ea3e923d56c6497eac9.war\"
from Service Module Loader]
        at
org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
        at
org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at
org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at
org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 42 more
"}}}}
```

**Comment by manovotn** [comment]
> Basically all of the invoker tests appear to be failing with a CNFE on jakarta.enterprise.inject.build.compatible.spi.InvokerFactory, so the wildfly modules must not be updated correctly or something is missing. 

Yes, see my previous comment :)
https://github.com/jakartaee/cdi-tck/issues/558#issuecomment-1970783717

**Comment by manovotn** [comment]
@starksm64 Yes, I was able to reproduce immediately even without the TCK `dist-build`.
After some more digging, the `@ShouldThrowException` marks the deployment as `testable=false` by default.
This is what triggers the TCK behavior as well and why Weld fails.

I do not think this is something we can fix on Weld side - it seems that tests expecting a failure should be running as `testable=false` and as such will need to avoid using nested classes.

**Comment by starksm64** [comment]
Ok, I'll move that test back to not using nested classes.
